services:
  api:
    build: .
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    ports:
      - "80:80"
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net: